# Generated by Django 2.0.5 on 2019-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='普通会员表',
            name='生日',
            field=models.DateField(blank=True, null=True),
        ),
    ]
